# -*- coding: utf-8 -*-
"""compare.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NuIHQy1yNulEpZcL1eQJgmMAmGNEIAwV
"""

def sort_dicts(data, key):
    """
    Sort a list of dictionaries based on a specified key.

    Parameters:
    data (list): List of dictionaries to sort.
    key (str): The key to sort dictionaries by.

    Returns:
    list: Sorted list of dictionaries.
    """
    return sorted(data, key=lambda x: x[key])

# Sample data for testing
data = [
    {'name': 'Alice', 'age': 25},
    {'name': 'Bob', 'age': 20},
    {'name': 'Charlie', 'age': 30}
]

# Test the function
sorted_data = sort_dicts(data, 'age')
print(sorted_data)

def sort_dicts_inplace(data, key):
    """
    Sort a list of dictionaries in place based on a specified key.

    Parameters:
    data (list): List of dictionaries to sort.
    key (str): The key to sort dictionaries by.
    """
    data.sort(key=lambda x: x[key])

# Reset sample data
data = [
    {'name': 'Alice', 'age': 25},
    {'name': 'Bob', 'age': 20},
    {'name': 'Charlie', 'age': 30}
]

# Test the in-place sort function
sort_dicts_inplace(data, 'age')
print(data)